version: "3"
services:
  app:
    image: hostlab/hostlab:latest
    ports:
      - 127.0.0.10:8080:8080
    networks:
      - app
      - users
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb://db/hostlab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  db:
    image: mvertes/alpine-mongo:latest
    networks:
      - app
    volumes:
      - ./db:/data/db:rw
networks:
  app:
    driver: bridge
  users:
    driver: bridge
